### PR TITLE
Fix Go To Definition for symbols inside jars

### PR DESCRIPTION
**Pull request by daplf**
Seems to fix https://github.com/fwcd/kotlin-language-server/issues/263

[This](https://github.com/JetBrains/kotlin/commit/57a674e9e6be67cce2efa5b7352890e9f970ede4#diff-daf7679f3a63204ff6ee82e5fd4b57888298f44b6a39e1d9ee6ba9ba89b7da91L189-R189) might be why it stopped working. Not actually sure 😐

### CODE REVIEW

**Comment by medwards** [comment]
This definitely improves things! I can look up definitions in dependencies (like `ApplicationListener`). Some of them look a bit weird (like databinding annotation `JsonDeserialize` being empty) but still an improvement.

Java standard types like `UUID` don't work at all, but I suppose that is a separate problem.

**Comment by daplf** [comment]
> Some of them look a bit weird (like databinding annotation JsonDeserialize being empty) but still an improvement.

I think this was already a problem, but I could be wrong. At least when I was debugging this, the old builds (the ones before the bug) already showed empty definitions on annotations. I don't know if the current decompiler is complete in that regard.

> Java standard types like UUID don't work at all, but I suppose that is a separate problem

I just checked this on the old build as well and it's not working there either, so I guess it never worked at all.

**Comment by fwcd** [comment]
Pretty cool, thanks for investigating this issue and for the fix!

In the long term we might want to find a way to support this with the new class-reading-mechanism, but for now it's definitely nice to have go-to-definition work with libraries again.

**Comment by shipp02** [comment]
If go-to-definition works inside jars as well then we may also close (#217).

**Comment by daplf** [comment]
@shipp02 That issue is about actual source jars, which are not yet supported by this server. Go to definition works with jars at the moment but only through decompiling

**Pull request merged**
