### PR TITLE
Bump Kotlin to 2.0.0

### PR DESCRIPTION
**Pull request by AlexandrosAlexiou**
- Bump Kotlin version to `2.0.0` to the related Gradle files

### CODE REVIEW

**Comment by AlexandrosAlexiou** [comment]
This PR is an attempt to bump the kotlin version to 2.0.0 and ultimately start making myself familiar with the codebase as I would be interested in supporting the project.

That being said, I am noticing an issue with [this](https://github.com/fwcd/kotlin-language-server/blob/bdba774daa2f4113a723b7a2d07d696be3b563cf/server/src/test/kotlin/org/javacs/kt/AdditionalWorkspaceTest.kt#L31) test **not** passing right now, but I created the PR anyway to spark the discussion.

It seems that hovering over the `assertTrue` method just return `null`.

I packaged the server after the update and instantiated it from Neovim, and it seems that it works, but the hovering over `assertTrue` just returns null as in the test.

Any idea what might be the issue here?

**Comment by fwcd** [comment]
Thanks for looking into this, very much appreciated! It would be nice if you could split out the refactorings/cleanups into smaller commits for easier reviewability.

Regarding the failing test, you could try running `./gradlew test` with `--info` to get output. Looks like it can't find JUnit for some reason, a wild guess would be that you'd have to bump the Kotlin version in the test workspace too (under server/src/test/resources/additionalWorkspace)

**Comment by AlexandrosAlexiou** [comment]
> Thanks for looking into this, very much appreciated! It would be nice if you could split out the refactorings/cleanups into smaller commits for easier reviewability.
> 
> Regarding the failing test, you could try running `./gradlew test` with `--info` to get output. Looks like it can't find JUnit for some reason, a wild guess would be that you'd have to bump the Kotlin version in the test workspace too (under server/src/test/resources/additionalWorkspace)

Hey! Thanks for the reply. 
I have bumped it [here](https://github.com/fwcd/kotlin-language-server/pull/576/files#diff-fba3b8cca43d04352f169f20e1c3c93ef0c3495b5014a35617479b141f1ed0a2). It seems that this test is failing even in the main branch. Could you verify please?

**Comment by AlexandrosAlexiou** [comment]
Hello, turns out it was an issue that I still do not understand, but now all the tests are passing.
Please check so that we can move forward with this MR.

**Comment by AlexandrosAlexiou** [comment]
Closing this PR, opened a new one to bump version to 2.0.10.

**Pull request closed without merging**
