### PR TITLE
Infix code completion

### LINKED ISSUE #446: Code completion when typing infix method
Hi!
When I am trying to type an infix method like this:
image
I do not get any completion, (I'm in Neovim, but VSCode has the same behaviour).

Is there any plans to add completion for infix methods, or could you point me to a direction to possibly add it myself? Because I didn't find it in the roadmap, and IntelliJ does have it.
Thank you!

### PR DESCRIPTION
**Pull request by ElamC**
Closes #446

Adds missing completions for infix functions.

### CODE REVIEW

**Comment by fwcd** [comment]
Neat, thanks a lot for looking into this! Bit short on time, so I won't review it in detail right now, but it looks pretty good from a first glance (thanks for adding tests too).

**Review by themkat — APPROVED** [review]
Tested it manually as well, and works great 🙂 Good job! 🎉 

The only little case that is not working is when completing nothing (i.e, `1 ` instead of `1 a`, where the last gives us `and` as an alternative). The server is not generally good at handling these cases, so think we might need bigger rewrites to make it work. Maybe we should consider it future work and make an issue for it? I have been missing global completion with EVERYTHING when completing nothing, but unsure if it is just me or not...

**Comment by ElamC** [comment]
> Tested it manually as well, and works great 🙂 Good job! 🎉
> 
> The only little case that is not working is when completing nothing (i.e, `1 ` instead of `1 a`, where the last gives us `and` as an alternative). The server is not generally good at handling these cases, so think we might need bigger rewrites to make it work. Maybe we should consider it future work and make an issue for it? I have been missing global completion with EVERYTHING when completing nothing, but unsure if it is just me or not...

Added global completions but seems like detekt isnt agreeing with these changes..

**Comment by themkat** [comment]
> > Tested it manually as well, and works great 🙂 Good job! 🎉
> > The only little case that is not working is when completing nothing (i.e, `1 ` instead of `1 a`, where the last gives us `and` as an alternative). The server is not generally good at handling these cases, so think we might need bigger rewrites to make it work. Maybe we should consider it future work and make an issue for it? I have been missing global completion with EVERYTHING when completing nothing, but unsure if it is just me or not...
> 
> Added global completions @themkat let me know how it looks. Detekt isn't agreeing with these changes so will need to look into that. Also could do with some work regarding performance?

Sorry for the late reply, will try to have a closer look tomorrow 🙂 Been busy with some other things... 🙁 

Looking at the detekt violations, it seems to me that those are because of the existing implementation more than what you have done. I would say that you use `@Suppress` with those methods for now (e.g, `@Suppress("ReturnCount")`). Sounds okay to you? Will let you know if I find some obvious fixes to the Detekt issues.

**Review by themkat — APPROVED** [review]
Can't see any obvious faults! Good job! Completing infix functions works amazing, especially globally! Thank you for amazing work! ❤️ Very happy to see that your changes are verified by both your own and existing tests. 


Sorry if I'm a downer with this last sentence... but.. I'm going to give @fwcd a day or two to have a look before merging. Like to give him a chance to have a look before merging, especially since he have his own set of opinions on code style etc. 🙂 (FWs repo after all)

**Comment by themkat** [comment]
It's been 2 days, so merging now. Thank you @ElamC 😄

**Pull request merged**
