### PR TITLE
Javadoc in hover messages (first revision)

### PR DESCRIPTION
**Pull request by Strum355**
Works for on call and declaration sites

### CODE REVIEW

**Comment by Strum355** [comment]
I believe this crashes and/or doesnt work with classes/objects yet

**Comment by Strum355** [comment]
Hovering over class constructor calls eg `val input = ExitOnClose(System.\`in\`)`, there is no problem and it shows the javadoc
Hovering over a class name at its declaration site, it throws the below exception. It only throws the exception if the previous hover hasnt been performed

https://hastebin.com/ayohoquxox.cs

**Comment by fwcd** [comment]
@Strum355 Thanks for your contribution, I won't merge the PR as long as it has a `WIP` tag though.

**Comment by Strum355** [comment]
https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocLocations.java this link would probably be useful, the vscode java extension seems to have issues with this repo so im having issues following it without having errors yelled at my face, but itd be a good start

**Comment by Strum355** [comment]
@fwcd has this functionality been added to master since this PR has been created or is this PR still good to have more work done to it?

**Comment by fwcd** [comment]
@Strum355 There is no equivalent functionality yet, so reviving this PR would be great. 👍

**Comment by Strum355** [comment]
Brought this PR up to speed, it doesnt work for some situations but we can remedy that in later cases. as far as im aware, this currently only works for call expressions and function declarations, but not for class signatures from what ive seen. Class signature hover in general doesnt work in all cases eg hovering `KotlinTextDocumentService` gives nothing while for other class definitions it does. 

This PR can be merged to give users at least *something* to begin with :)

**Pull request merged**
